apiVersion: v1                      # API version for ServiceAccount resource (v1 is the stable version)
kind: ServiceAccount                 # Resource type - ServiceAccount provides identity for pods
metadata:                            # Metadata section - contains identifying information
  name: my-serviceaccount           # Name of the ServiceAccount (must be unique within namespace)
  namespace: default                # Namespace where ServiceAccount will be created (optional, defaults to 'default')
  labels:                           # Labels are key-value pairs used for selecting and organizing resources
    app: nginx                      # Label: application name
    account-type: application        # Label: account type
  annotations:                      # Annotations are metadata that don't affect resource behavior
    description: "Service account for nginx pods"  # Custom annotation: human-readable description
    # Cloud provider specific annotations:
    # AWS EKS:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/my-role  # IAM role ARN for pod identity
    # GCP GKE:
    # iam.gke.io/gcp-service-account: my-service@project.iam.gserviceaccount.com  # GCP service account
    # Azure AKS:
    # azure.workload.identity/client-id: "12345678-1234-1234-1234-123456789012"  # Azure client ID
automountServiceAccountToken: true   # Automatically mount service account token (default: true)
                                    # When false, pods using this SA won't get mounted token
imagePullSecrets:                   # List of image pull secrets (optional)
                                    # Used to pull images from private registries
- name: docker-registry-secret      # Secret name containing Docker registry credentials
                                    # Secret must be of type kubernetes.io/dockerconfigjson

---
# Example: ServiceAccount without token mounting
apiVersion: v1
kind: ServiceAccount
metadata:
  name: no-token-sa
  namespace: default
automountServiceAccountToken: false  # Don't mount service account token
                                    # Useful for pods that don't need Kubernetes API access

---
# Example: ServiceAccount with image pull secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: private-registry-sa
  namespace: default
imagePullSecrets:                   # Image pull secrets for private registries
- name: dockerhub-secret            # Secret for Docker Hub
- name: gcr-secret                  # Secret for Google Container Registry
- name: ecr-secret                  # Secret for AWS ECR

---
# Example: ServiceAccount for AWS EKS (IRSA - IAM Roles for Service Accounts)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/my-app-role  # IAM role ARN
automountServiceAccountToken: true   # Must be true for IRSA to work

---
# Example: ServiceAccount for GCP GKE (Workload Identity)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcp-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: my-app@my-project.iam.gserviceaccount.com  # GCP service account
automountServiceAccountToken: true   # Must be true for Workload Identity to work

---
# Example: ServiceAccount for Azure AKS (Workload Identity)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "12345678-1234-1234-1234-123456789012"  # Azure client ID
automountServiceAccountToken: true   # Must be true for Workload Identity to work

