apiVersion: apiextensions.k8s.io/v1  # API version for CustomResourceDefinition resource (apiextensions.k8s.io/v1 is the stable version)
kind: CustomResourceDefinition        # Resource type - CRD defines custom resources in Kubernetes
metadata:                             # Metadata section - contains identifying information
  name: databases.example.com         # Name of the CRD (must be unique cluster-wide)
                                    # Format: <plural>.<group> (e.g., databases.example.com)
  labels:                            # Labels are key-value pairs used for selecting and organizing resources
    crd: database                    # Label: CRD type
  annotations:                       # Annotations are metadata that don't affect resource behavior
    description: "Database custom resource"  # Custom annotation: human-readable description
  # Note: CRD is cluster-scoped, so no namespace field
spec:                                 # Specification section - defines desired state
  group: example.com                 # API group name (required)
                                    # Used in API version: <group>/<version>
  names:                             # Names for the custom resource (required)
    plural: databases                # Plural name (required) - used in URLs: /apis/example.com/v1/databases
    singular: database               # Singular name (required) - used in kubectl: kubectl get database
    kind: Database                   # Kind name (required) - used in YAML: kind: Database
    shortNames:                      # Short names (optional) - used in kubectl: kubectl get db
    - db                             # Short name 1
    - dbs                            # Short name 2
    listKind: DatabaseList           # List kind name (optional, defaults to <kind>List)
    categories:                      # Categories (optional) - groups resources together
    - databases                      # Category name
  scope: Namespaced                  # Scope: Namespaced or Cluster (required)
                                    # Namespaced: resource exists within namespaces
                                    # Cluster: resource is cluster-scoped
  versions:                          # List of API versions (required)
  - name: v1                         # Version name (required)
    served: true                     # Served: whether this version is served by API server (required)
    storage: true                    # Storage: whether this version is used for storage (required)
                                    # Only one version can have storage: true
    deprecated: false                # Deprecated: whether this version is deprecated (default: false)
    deprecationWarning: ""           # Deprecation warning message (optional)
    schema:                          # OpenAPI schema (required)
      openAPIV3Schema:               # OpenAPI v3 schema
        type: object                 # Root type: object
        properties:                  # Properties of the object
          spec:                      # Spec property
            type: object
            properties:
              databaseName:          # Database name property
                type: string
                description: "Name of the database"
                minLength: 1
                maxLength: 63
              engine:               # Database engine property
                type: string
                enum:               # Allowed values
                - mysql
                - postgresql
                - mongodb
                description: "Database engine type"
              version:              # Database version property
                type: string
                description: "Database version"
              replicas:             # Replicas property
                type: integer
                minimum: 1
                maximum: 10
                default: 1
                description: "Number of database replicas"
              storage:              # Storage property
                type: object
                properties:
                  size:             # Storage size
                    type: string
                    pattern: '^[0-9]+(Gi|Mi)$'  # Pattern: number followed by Gi or Mi
                    description: "Storage size (e.g., 10Gi)"
                  storageClass:     # Storage class
                    type: string
                    description: "Storage class name"
            required:                # Required properties
            - databaseName
            - engine
            - version
          status:                    # Status property
            type: object
            properties:
              phase:                # Phase property
                type: string
                enum:
                - Pending
                - Running
                - Failed
                description: "Database phase"
              ready:                # Ready property
                type: boolean
                description: "Whether database is ready"
              endpoints:            # Endpoints property
                type: array
                items:
                  type: string
                description: "Database endpoints"
        required:                    # Required root properties
        - spec
    subresources:                    # Subresources (optional)
      status: {}                    # Status subresource (enables /status endpoint)
      # scale:                      # Scale subresource (optional, for scaling)
      #   specReplicasPath: .spec.replicas
      #   statusReplicasPath: .status.replicas
      #   labelSelectorPath: .status.selector
    additionalPrinterColumns:       # Additional printer columns (optional)
                                    # Customizes kubectl get output
    - name: Engine                  # Column name
      type: string                  # Column type: integer, number, string, boolean, date
      description: "Database engine"
      jsonPath: .spec.engine        # JSON path to value
      priority: 0                   # Priority (0 = highest)
    - name: Version
      type: string
      description: "Database version"
      jsonPath: .spec.version
      priority: 0
    - name: Replicas
      type: integer
      description: "Number of replicas"
      jsonPath: .spec.replicas
      priority: 0
    - name: Phase
      type: string
      description: "Database phase"
      jsonPath: .status.phase
      priority: 1
    - name: Age
      type: date
      description: "Creation timestamp"
      jsonPath: .metadata.creationTimestamp
      priority: 0
  - name: v1alpha1                  # Another version (older version)
    served: true                    # Still served
    storage: false                  # Not used for storage (v1 is storage version)
    deprecated: true                # Deprecated
    deprecationWarning: "v1alpha1 is deprecated, use v1"
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              databaseName:
                type: string
              engine:
                type: string
        required:
        - spec
  conversion:                        # Conversion strategy (optional)
    strategy: None                   # Strategy: None or Webhook
                                    # None: no conversion (all versions must be compatible)
                                    # Webhook: use webhook for conversion
    # webhook:                      # Webhook configuration (for Webhook strategy)
    #   clientConfig:
    #     service:
    #       namespace: default
    #       name: conversion-webhook
    #       path: /convert
    #   conversionReviewVersions:
    #   - v1
  preserveUnknownFields: false      # Preserve unknown fields (default: true in v1beta1, false in v1)
                                    # When false, unknown fields are dropped

---
# Example: Simple CRD without status
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.example.com
spec:
  group: example.com
  names:
    plural: websites
    singular: website
    kind: Website
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              url:
                type: string
              title:
                type: string
            required:
            - url
        required:
        - spec

---
# Example: Cluster-scoped CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.example.com
spec:
  group: example.com
  names:
    plural: clusters
    singular: cluster
    kind: Cluster
  scope: Cluster                    # Cluster-scoped
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
              provider:
                type: string
        required:
        - spec

---
# Example: CRD with scale subresource
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.example.com
spec:
  group: example.com
  names:
    plural: apps
    singular: app
    kind: App
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
          status:
            type: object
            properties:
              replicas:
                type: integer
              selector:
                type: string
        required:
        - spec
    subresources:
      status: {}
      scale:                         # Scale subresource
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
        labelSelectorPath: .status.selector

